"""empty message

Revision ID: a01a823022da
Revises: 
Create Date: 2020-06-26 11:32:00.735994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01a823022da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('comment', sa.Column('edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'edited')
    op.drop_column('blog_post', 'edited')
    # ### end Alembic commands ###
