"""empty message

Revision ID: f625054ccd8a
Revises: 
Create Date: 2020-06-27 13:52:47.782928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f625054ccd8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('date_published', sa.DateTime(), nullable=True))
    op.add_column('blog_post', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'is_published')
    op.drop_column('blog_post', 'date_published')
    # ### end Alembic commands ###
